Various C++ Examples (including IPC): overload.cc File Reference
overload.cc File Reference
simple overloading example
#include <stdio.h>
Functions
int thing1 ()
int thing1 (int i)
double thing2 ()
double thing2 (int i)
int main (int argc, char **argv)
Detailed Description
simple overloading example
Definition in file overload.cc.
Function Documentation
int main (int argc, char ** argv)
Definition at line 37 of file overload.cc.
References thing1(), and thing2().
 {
   int x;
   double y;
   x = thing1();
   x = thing1(1);
   y = thing2();
   y = thing2(1);
 }
int thing1 ()
Definition at line 12 of file overload.cc.
Referenced by main().
 {
   printf( "thing1\n");
   return 1;
 }
int thing1 (int i)
Definition at line 18 of file overload.cc.
 {
   printf( "thing1a\n" );
   return 0;
 }
double thing2 ()
Definition at line 24 of file overload.cc.
Referenced by main().
 {
   printf( "thing2\n");
   return 'x';
 }
double thing2 (int i)
Definition at line 29 of file overload.cc.
 {
   printf( "thing2a\n" );
   return 0;
 }