Various C++ Examples (including IPC): threadDeath1.cc File Reference
threadDeath1.cc File Reference
basic thread functionality
#include <pthread.h>
#include <iostream>
#include <cstring>
Macros
#define CHAR_EXAMPLE
make this a define to use the char * example
Functions
void * myfunc (void *arg)
user defined function to call
void * func (void *arg)
a function that calls the user defined function
int main (int argc, char *argv[])
Detailed Description
basic thread functionality
Purpose:
Example program that creates a thread that uses a function that calls a user defined function. Also demonstrates casing examples for the pthread_join(void **) return type. Often the return type from pthread_join() is confusing so we demonstrate a char* or a string* depending on whether CHAR_EXAMPLE is defined within this file (see below).
The intention here is that we want to demonstrate passing pointers around when creating threads and then accessing those pointers as we go allong.
Definition in file threadDeath1.cc.
Macro Definition Documentation
#define CHAR_EXAMPLE
make this a define to use the char * example
Definition at line 24 of file threadDeath1.cc.
Function Documentation
void* func (void * arg)
a function that calls the user defined function
See myfunc for more details. This function does, however use pthread_exit() to demonstrate the passing of the return_value pointer back through pthread_join() in main
Definition at line 69 of file threadDeath1.cc.
References myfunc().
Referenced by main().
 {
   void *return_value = myfunc(arg);
   pthread_exit(return_value);
 }
int main (int argc, char * argv[])
Definition at line 81 of file threadDeath1.cc.
References func(), and myfunc().
 {
   //a thread id
   pthread_t tid;
   //return var from a pthread_exit()/pthread_join()
   void **ret;
   //a string to pass to myfunc()
   string arg("string from main");
   //##########################################################
   //##########################################################
   cout << "example 1:" << endl;
   //##########################################################
   //call a function tha calls the function
   pthread_create(&tid, (pthread_attr_t *)NULL, func, (void *)&arg);
   //join the thread
   pthread_join(tid, ret);
 #ifdef CHAR_EXAMPLE
   //demonstrate a char * example
   char *pc = ((char *)(char *)*ret);
   cout << pc << endl;
   delete pc;
 #else
   //demonstrate a string * example
   string *ps = ((string *)(string *)*ret);
   cout << *ps << endl;
   delete (string *)ps;
 #endif
   //##########################################################
   //##########################################################
   /* Same type of example as above: this one just calls the function
   directly and uses more direct casting when accesing the return
   value from the function.
   */
   //##########################################################
   cout << "\n" << "example 2:" << endl;
   //##########################################################
   //creat thread
   pthread_create(&tid, (pthread_attr_t *)NULL, myfunc, (void *)&arg);
   //join thread
   pthread_join(tid, ret);
 #ifdef CHAR_EXAMPLE
   //access char through casts
   cout << ((char *)(char *)*ret) << endl;
   delete ((char *)(char *)*ret);
 #else
   //access string through casts
   cout << *((string *)(string *)*ret) << endl;
   delete ((string *)(string *)*ret);
 #endif
   return 0;
 }
void * myfunc (void * arg)
user defined function to call
Purpose:
A user defined function. This function, for demonstration purposes, dynamically creates a string object that will be returned through a call to pthread_join() later on.
Note
This function SHOULD NOT call pthread_exit() as it is intended, in this case, to return to the wrapper function func(). Calling pthread_exit() from here will terminate the thread and will result in "undefined behavior".
Parameters
arg is a string object pointer passed in as a void *
Returns
a string object that is dynamically allocated
Returns
some object from the heap
Parameters
some object
Note
this function assumes that arg is a string pointer passed in from main -for demonstration purposes
 \warning do NOT call pthread_exit from here! This function will
behave the same if it is called directly or not and a returning normally does not affect the return_value parameter of a pthread_join().
Definition at line 28 of file threadDeath1.cc.
Referenced by func(), and main().
 {
   //print whatever is in arg as a string
   cout << *(string *)arg << endl;
 #ifdef CHAR_EXAMPLE
   //demonstrate a char * return
   char *c = new char[256];
   memset(c, 0, 256);
   strcpy(c,"string from myfunc");
   cout << "myfunc returning:" << c <<endl;
   //pthread_exit((void *)c);
   return( (void *)c);
 #else
   //demonstrate a string * return.
   string *s = new string("string from myfunc");
   cout << "myfunc returning:" << *s <<endl;
   /* DO NOT CALL pthread_exit from here */
   //pthread_exit((void *)s);
   return( (void *)s);
 #endif
 }