Various C++ Examples (including IPC): virtuals.cc File Reference
virtuals.cc File Reference
basic virtual function / class usage
#include <iostream>
Classes
class AbstractClass
A basic abstract Class (that is inherited from)
class BaseClass
class that inherits from AbstractClass
class ChildClass
class that inherits from BaseClass -> AbstractClass
class AnotherChildClass
another example of ChildClass (inherits from BaseClass)
Functions
void callPrint (AbstractClass &p)
print something
int main (int argc, char **argv)
demonstrate virtual functions and abstract classes
Detailed Description
basic virtual function / class usage
Definition in file virtuals.cc.
Function Documentation
void callPrint (AbstractClass & p)
print something
Definition at line 46 of file virtuals.cc.
References AbstractClass::print().
Referenced by main().
 {
   //call the appropriat function (based on the actual type of
   //BaseClass -be it derived or not)
   p.print();
 }
int main (int argc, char ** argv)
demonstrate virtual functions and abstract classes
Definition at line 54 of file virtuals.cc.
References callPrint().
 {
   BaseClass b;
   ChildClass c;
   AnotherChildClass a;
   //concrete behavior
   callPrint(b);
   //polymorphic behavior
   callPrint(c);
   //concrete (hiarchial) behavior
   callPrint(a);
 }